service: privreg

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
functions:
  api:
    handler: handler.index
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY